# Generated by Django 5.1 on 2024-09-06 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_category_subscribers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
    ]
